allowBuilds:
  '@biomejs/biome': true
minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.107.0'
  - '@supabase/functions-js@2.107.0'
  - '@supabase/postgrest-js@2.107.0'
  - '@supabase/realtime-js@2.107.0'
  - '@supabase/storage-js@2.107.0'
  - '@supabase/supabase-js@2.107.0'
  - '@tanstack/query-core@5.101.0'
  - '@tanstack/react-query@5.101.0'
